/**
 * This code was generated by "react-native codegen-harmony"
 * 
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 * 
 * @generatorVersion: 1
 */


export namespace RTNCameraTurboModule {
  export const NAME = 'RTNCameraTurboModule' as const

  export type HardwareCamera = {deviceType?: string, id: string, type: number}
  
  export type TakePictureOptions = {quality?: number, base64?: boolean, exif?: boolean, width?: number, mirrorImage?: boolean, doNotSave?: boolean, pauseAfterCapture?: boolean, fixOrientation?: boolean, forceUpOrientation?: boolean, imageType?: string, path?: string}
  
  export type TakePictureResponse = {width: number, height: number, uri: string, base64?: string, pictureOrientation: number, deviceOrientation: number}
  
  export type RecordOptions = {quality?: string, orientation?: Object, maxDuration?: number, maxFileSize?: number, mute?: boolean, mirrorVideo?: boolean, path?: string, videoBitrate?: number, codec?: string, fps?: number}
  
  export type RecordResponse = {uri: string, videoOrientation: number, deviceOrientation: number, isRecordingInterrupted: boolean, codec?: string}
  
  export interface Spec {
    requestDeviceCameraAuthorization(): Promise<boolean>;
  
    checkDeviceCameraAuthorizationStatus(): boolean;
  
    checkMicrophoneAccessStatus(): boolean;
  
    requestMicrophonePermission(): Promise<boolean>;
  
    getAvailableCameraDevices(): {cameraId: string, cameraPosition: string, cameraType: number}[];
  
    getCameraIds(): HardwareCamera[];
  
    takePictureAsync(options: TakePictureOptions): Promise<TakePictureResponse>;
  
    recordAsync(options: RecordOptions): Promise<RecordResponse>;
  
    refreshAuthorizationStatus(): Promise<void>;
  
    stopRecording(): void;
  
    pausePreview(): void;
  
    resumePreview(): void;
  
    getAvailablePictureSizes(): Promise<string[]>;
  
    getCameraIdsAsync(): Promise<HardwareCamera[]>;
  
    getSupportedRatiosAsync(): Promise<string[]>;
  
    getSupportedPreviewFpsRange(): Promise<string[]>;
  
    checkIfVideoIsValid(): Promise<boolean>;
  
    isRecording(): Promise<boolean>;
  
  }
}
